version: '3.8'

services:
  player-service:
    build: .
    container_name: player-service
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # persist H2 DB file locally
    environment:
      - SPRING_PROFILES_ACTIVE=default
